# A generic, single database configuration.

[alembic]

# Path to migration scripts.
script_location = %(here)s/alembic

# Template used to generate migration file names.
# The default value is %%(rev)s_%%(slug)s
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# Python path.
prepend_sys_path = .

# Timezone to use when rendering the date.
# Leave blank for local time.
# timezone =

# Maximum length of characters in the slug.
# truncate_slug_length = 40

# Version location.
# version_locations = %(here)s/alembic/versions

# Path separator.
path_separator = os

# Search source files recursively.
# recursive_version_locations = false

# Output encoding.
# output_encoding = utf-8


# =========================================================
# DATABASE CONNECTION
# =========================================================

sqlalchemy.url = sqlite:///./doctor_patient.db


# =========================================================
# POST WRITE HOOKS
# =========================================================

[post_write_hooks]

# Format using black.
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# Lint using ruff.
# hooks = ruff
# ruff.type = module
# ruff.module = ruff
# ruff.options = check --fix REVISION_SCRIPT_FILENAME


# =========================================================
# LOGGING
# =========================================================

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic


[logger_root]
level = WARNING
handlers = console
qualname =


[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine


[logger_alembic]
level = INFO
handlers =
qualname = alembic


[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic


[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S